### ISSUE TITLE
css selector doesn't work if it insides <ul><form></form></ul>

### ISSUE THREAD

**Issue by haifengkao** [tid-kijyun/Kanna#245]
### Description:

cannot get `<input>` by css selector `ul input`
```
let str = """
<ul>
   <form>
         <input>
   </form>
  
</ul>
"""

let doc = try! Kanna.HTML(html: st, url: "", encoding: .utf8, option: kDefaultHtmlParseOption)
let nodes = doc.css("ul input")
let count = nodes.count

print(count) // count will be 0
```

change `form` to `form1` works
```
let str = """
<ul>
   <form1>
         <input>
   </form1>
  
</ul>
"""

let doc = try! Kanna.HTML(html: st, url: "", encoding: .utf8, option: kDefaultHtmlParseOption)
let nodes = doc.css("ul input")
let count = nodes.count

print(count) // count will be 1
```

change `ul` to `div` works
```
let str = """
<div>
   <form>
         <input>
   </form>
  
</div>
"""

let doc = try! Kanna.HTML(html: st, url: "", encoding: .utf8, option: kDefaultHtmlParseOption)
let nodes = doc.css("div input")
let count = nodes.count

print(count) // count will be 1
```

### Installation method:

- [ ] CocoaPods

### Kanna version (or commit hash):
5.2.3

### swift --version
Apple Swift version 5.3.1 (swiftlang-1200.0.39 clang-1200.0.32.6)

### Xcode version (optional):
12.2 beta

**Comment by tid-kijyun** [comment]
@haifengkao Thank you for your report.

This is a specification.
This happens because Kanna parses the input as HTML4. According to the HTML 4 specification, we can't put an `input` tag directly under a `form` tag. I think it will work if you enclose the `input` tag with a `p` tag or something like that.

**Workaround:** If you can't change the input HTML, please parse it as XML. The input is out of the XML specification (The `input` tag is not closed.), but it works.

```swift
let str = """
<ul>
   <form>
         <input>
   </form>
  
</ul>
"""

let doc = try! Kanna.XML(xml: str, url: "", encoding: .utf8)
let nodes = doc.css("ul input")
let count = nodes.count

print(count) // count will be 1
```

**Comment by haifengkao** [comment]
thanks
